Add autoHidePlayer prop
ihmpavel/expo-video-player pull request #506
Opened 2021-11-12 04:04 UTC by hungvu193

Sometimes, When I drag the slider on IOS, it will be disappeared due to controlsTimer hide animation (default 200ms).
This prop will prevent it.

2021-11-13 22:14 UTC, ihmpavel requested changes
Looks good, but you should edit files in `/lib` folder

2021-11-13 22:14 UTC, ihmpavel commented on dist/index.js
> +    };
This looks like a duplicated line by mistake

2021-11-13 22:14 UTC, ihmpavel commented on dist/index.js
> +        if (controlsTimer === null && props.autoHidePlayer) {
If you want to change/add something, update please Typescript files located under `lib` folder.

In your case `props.ts` and `index.ts`. After that run `yarn build`. That will generate JS files in `/dist` folder and TS definitions. Update also props documentation in `README.md`

I'll be happy to accept this MR

2021-11-14 15:16 UTC, hungvu193 commented on dist/index.js
> +        if (controlsTimer === null && props.autoHidePlayer) {
got it, let me update my PR

2021-11-16 05:25 UTC, hungvu193 commented
@ihmpavel let have a look, I have just updated the PR 😄

2021-11-26 02:52 UTC, merged